# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.workers.max=4
kotlin.compiler.execution.strategy=in-process

# Enable R8 Full Mode for optimal code shrinking and performance
android.enableR8.fullMode=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
